name: rxget_lint
description: Custom lint rules for rxget to enforce RxState patterns.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=5.0.0 <7.0.0"
  custom_lint_builder: ^0.6.0
  analyzer_plugin: ^0.11.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
