name: rxget
description: A lightweight reactive state management and dependency injection library for Dart and Flutter â€” pure and minimal.
version: 0.1.0+3
homepage: https://github.com/sugithGit/rxget

environment:
  sdk: ">=3.10.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ">=1.0.0 <2.0.0"

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  custom_lint: ^0.6.4
  rxget_lint:
    path: ../rxget_lint
